/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminappRouteImport } from './routes/_adminapp'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteBanglesRouteImport } from './routes/_site/bangles'
import { Route as SiteBraceletsRouteImport } from './routes/_site/bracelets'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteDiamondJewelleryRouteImport } from './routes/_site/diamond-jewellery'
import { Route as SiteEarringsRouteImport } from './routes/_site/earrings'
import { Route as SiteGemstonesRouteImport } from './routes/_site/gemstones'
import { Route as SiteGiftsRouteImport } from './routes/_site/gifts'
import { Route as SiteGoldJewelleryRouteImport } from './routes/_site/gold-jewellery'
import { Route as SiteJewelleryRouteImport } from './routes/_site/jewellery'
import { Route as SiteNecklacesRouteImport } from './routes/_site/necklaces'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteReviewsRouteImport } from './routes/_site/reviews'
import { Route as SiteRingsRouteImport } from './routes/_site/rings'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as SiteWishlistRouteImport } from './routes/_site/wishlist'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminappAdminIndexRouteImport } from './routes/_adminapp/admin.index'
import { Route as AdminappAdminProductsRouteImport } from './routes/_adminapp/admin.products'
import { Route as SiteCollectionSlugRouteImport } from './routes/_site/collection.$slug'
import { Route as SiteProductsSlugRouteImport } from './routes/_site/products.$slug'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const AdminappRoute = AdminappRouteImport.update({
  id: '/_adminapp',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteBanglesRoute = SiteBanglesRouteImport.update({
  id: '/bangles',
  path: '/bangles',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteBraceletsRoute = SiteBraceletsRouteImport.update({
  id: '/bracelets',
  path: '/bracelets',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteDiamondJewelleryRoute = SiteDiamondJewelleryRouteImport.update({
  id: '/diamond-jewellery',
  path: '/diamond-jewellery',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEarringsRoute = SiteEarringsRouteImport.update({
  id: '/earrings',
  path: '/earrings',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteGemstonesRoute = SiteGemstonesRouteImport.update({
  id: '/gemstones',
  path: '/gemstones',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteGiftsRoute = SiteGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteGoldJewelleryRoute = SiteGoldJewelleryRouteImport.update({
  id: '/gold-jewellery',
  path: '/gold-jewellery',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteJewelleryRoute = SiteJewelleryRouteImport.update({
  id: '/jewellery',
  path: '/jewellery',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteNecklacesRoute = SiteNecklacesRouteImport.update({
  id: '/necklaces',
  path: '/necklaces',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteReviewsRoute = SiteReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteRingsRoute = SiteRingsRouteImport.update({
  id: '/rings',
  path: '/rings',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteWishlistRoute = SiteWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminappAdminIndexRoute = AdminappAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminappRoute,
} as any)
const AdminappAdminProductsRoute = AdminappAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AdminappRoute,
} as any)
const SiteCollectionSlugRoute = SiteCollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteProductsSlugRoute = SiteProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/bangles': typeof SiteBanglesRoute
  '/bracelets': typeof SiteBraceletsRoute
  '/contact': typeof SiteContactRoute
  '/diamond-jewellery': typeof SiteDiamondJewelleryRoute
  '/earrings': typeof SiteEarringsRoute
  '/gemstones': typeof SiteGemstonesRoute
  '/gifts': typeof SiteGiftsRoute
  '/gold-jewellery': typeof SiteGoldJewelleryRoute
  '/jewellery': typeof SiteJewelleryRoute
  '/necklaces': typeof SiteNecklacesRoute
  '/privacy': typeof SitePrivacyRoute
  '/reviews': typeof SiteReviewsRoute
  '/rings': typeof SiteRingsRoute
  '/terms': typeof SiteTermsRoute
  '/wishlist': typeof SiteWishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminappAdminProductsRoute
  '/collection/$slug': typeof SiteCollectionSlugRoute
  '/products/$slug': typeof SiteProductsSlugRoute
  '/admin/': typeof AdminappAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/bangles': typeof SiteBanglesRoute
  '/bracelets': typeof SiteBraceletsRoute
  '/contact': typeof SiteContactRoute
  '/diamond-jewellery': typeof SiteDiamondJewelleryRoute
  '/earrings': typeof SiteEarringsRoute
  '/gemstones': typeof SiteGemstonesRoute
  '/gifts': typeof SiteGiftsRoute
  '/gold-jewellery': typeof SiteGoldJewelleryRoute
  '/jewellery': typeof SiteJewelleryRoute
  '/necklaces': typeof SiteNecklacesRoute
  '/privacy': typeof SitePrivacyRoute
  '/reviews': typeof SiteReviewsRoute
  '/rings': typeof SiteRingsRoute
  '/terms': typeof SiteTermsRoute
  '/wishlist': typeof SiteWishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminappAdminProductsRoute
  '/collection/$slug': typeof SiteCollectionSlugRoute
  '/products/$slug': typeof SiteProductsSlugRoute
  '/admin': typeof AdminappAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteRouteWithChildren
  '/_adminapp': typeof AdminappRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/bangles': typeof SiteBanglesRoute
  '/_site/bracelets': typeof SiteBraceletsRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/diamond-jewellery': typeof SiteDiamondJewelleryRoute
  '/_site/earrings': typeof SiteEarringsRoute
  '/_site/gemstones': typeof SiteGemstonesRoute
  '/_site/gifts': typeof SiteGiftsRoute
  '/_site/gold-jewellery': typeof SiteGoldJewelleryRoute
  '/_site/jewellery': typeof SiteJewelleryRoute
  '/_site/necklaces': typeof SiteNecklacesRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/reviews': typeof SiteReviewsRoute
  '/_site/rings': typeof SiteRingsRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/wishlist': typeof SiteWishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/_site/': typeof SiteIndexRoute
  '/_adminapp/admin/products': typeof AdminappAdminProductsRoute
  '/_site/collection/$slug': typeof SiteCollectionSlugRoute
  '/_site/products/$slug': typeof SiteProductsSlugRoute
  '/_adminapp/admin/': typeof AdminappAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bangles'
    | '/bracelets'
    | '/contact'
    | '/diamond-jewellery'
    | '/earrings'
    | '/gemstones'
    | '/gifts'
    | '/gold-jewellery'
    | '/jewellery'
    | '/necklaces'
    | '/privacy'
    | '/reviews'
    | '/rings'
    | '/terms'
    | '/wishlist'
    | '/admin/login'
    | '/admin/products'
    | '/collection/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bangles'
    | '/bracelets'
    | '/contact'
    | '/diamond-jewellery'
    | '/earrings'
    | '/gemstones'
    | '/gifts'
    | '/gold-jewellery'
    | '/jewellery'
    | '/necklaces'
    | '/privacy'
    | '/reviews'
    | '/rings'
    | '/terms'
    | '/wishlist'
    | '/admin/login'
    | '/admin/products'
    | '/collection/$slug'
    | '/products/$slug'
    | '/admin'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/_site'
    | '/_adminapp'
    | '/_site/about'
    | '/_site/bangles'
    | '/_site/bracelets'
    | '/_site/contact'
    | '/_site/diamond-jewellery'
    | '/_site/earrings'
    | '/_site/gemstones'
    | '/_site/gifts'
    | '/_site/gold-jewellery'
    | '/_site/jewellery'
    | '/_site/necklaces'
    | '/_site/privacy'
    | '/_site/reviews'
    | '/_site/rings'
    | '/_site/terms'
    | '/_site/wishlist'
    | '/admin/login'
    | '/_site/'
    | '/_adminapp/admin/products'
    | '/_site/collection/$slug'
    | '/_site/products/$slug'
    | '/_adminapp/admin/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  AdminappRoute: typeof AdminappRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_adminapp': {
      id: '/_adminapp'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/bangles': {
      id: '/_site/bangles'
      path: '/bangles'
      fullPath: '/bangles'
      preLoaderRoute: typeof SiteBanglesRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/bracelets': {
      id: '/_site/bracelets'
      path: '/bracelets'
      fullPath: '/bracelets'
      preLoaderRoute: typeof SiteBraceletsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/diamond-jewellery': {
      id: '/_site/diamond-jewellery'
      path: '/diamond-jewellery'
      fullPath: '/diamond-jewellery'
      preLoaderRoute: typeof SiteDiamondJewelleryRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/earrings': {
      id: '/_site/earrings'
      path: '/earrings'
      fullPath: '/earrings'
      preLoaderRoute: typeof SiteEarringsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/gemstones': {
      id: '/_site/gemstones'
      path: '/gemstones'
      fullPath: '/gemstones'
      preLoaderRoute: typeof SiteGemstonesRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/gifts': {
      id: '/_site/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof SiteGiftsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/gold-jewellery': {
      id: '/_site/gold-jewellery'
      path: '/gold-jewellery'
      fullPath: '/gold-jewellery'
      preLoaderRoute: typeof SiteGoldJewelleryRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/jewellery': {
      id: '/_site/jewellery'
      path: '/jewellery'
      fullPath: '/jewellery'
      preLoaderRoute: typeof SiteJewelleryRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/necklaces': {
      id: '/_site/necklaces'
      path: '/necklaces'
      fullPath: '/necklaces'
      preLoaderRoute: typeof SiteNecklacesRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/reviews': {
      id: '/_site/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof SiteReviewsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/rings': {
      id: '/_site/rings'
      path: '/rings'
      fullPath: '/rings'
      preLoaderRoute: typeof SiteRingsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/wishlist': {
      id: '/_site/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof SiteWishlistRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminapp/admin/': {
      id: '/_adminapp/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminappAdminIndexRouteImport
      parentRoute: typeof AdminappRoute
    }
    '/_adminapp/admin/products': {
      id: '/_adminapp/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminappAdminProductsRouteImport
      parentRoute: typeof AdminappRoute
    }
    '/_site/collection/$slug': {
      id: '/_site/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof SiteCollectionSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/products/$slug': {
      id: '/_site/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof SiteProductsSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBanglesRoute: typeof SiteBanglesRoute
  SiteBraceletsRoute: typeof SiteBraceletsRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteDiamondJewelleryRoute: typeof SiteDiamondJewelleryRoute
  SiteEarringsRoute: typeof SiteEarringsRoute
  SiteGemstonesRoute: typeof SiteGemstonesRoute
  SiteGiftsRoute: typeof SiteGiftsRoute
  SiteGoldJewelleryRoute: typeof SiteGoldJewelleryRoute
  SiteJewelleryRoute: typeof SiteJewelleryRoute
  SiteNecklacesRoute: typeof SiteNecklacesRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteReviewsRoute: typeof SiteReviewsRoute
  SiteRingsRoute: typeof SiteRingsRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteWishlistRoute: typeof SiteWishlistRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteCollectionSlugRoute: typeof SiteCollectionSlugRoute
  SiteProductsSlugRoute: typeof SiteProductsSlugRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBanglesRoute: SiteBanglesRoute,
  SiteBraceletsRoute: SiteBraceletsRoute,
  SiteContactRoute: SiteContactRoute,
  SiteDiamondJewelleryRoute: SiteDiamondJewelleryRoute,
  SiteEarringsRoute: SiteEarringsRoute,
  SiteGemstonesRoute: SiteGemstonesRoute,
  SiteGiftsRoute: SiteGiftsRoute,
  SiteGoldJewelleryRoute: SiteGoldJewelleryRoute,
  SiteJewelleryRoute: SiteJewelleryRoute,
  SiteNecklacesRoute: SiteNecklacesRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteReviewsRoute: SiteReviewsRoute,
  SiteRingsRoute: SiteRingsRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteWishlistRoute: SiteWishlistRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteCollectionSlugRoute: SiteCollectionSlugRoute,
  SiteProductsSlugRoute: SiteProductsSlugRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

interface AdminappRouteChildren {
  AdminappAdminProductsRoute: typeof AdminappAdminProductsRoute
  AdminappAdminIndexRoute: typeof AdminappAdminIndexRoute
}

const AdminappRouteChildren: AdminappRouteChildren = {
  AdminappAdminProductsRoute: AdminappAdminProductsRoute,
  AdminappAdminIndexRoute: AdminappAdminIndexRoute,
}

const AdminappRouteWithChildren = AdminappRoute._addFileChildren(
  AdminappRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRouteRoute: SiteRouteRouteWithChildren,
  AdminappRoute: AdminappRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
